{% set name = "pangolin-opengl" %}
{% set version = "0.9.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4c57edfa7a380afa12565c1c2a3b6a61824769c11eedfca7bfa090e5cf8c1366

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - ninja
    - cmake
    - pkg-config
    - {{ cdt('libglvnd-egl') }}       # [linux]
    - {{ cdt('libglvnd-devel') }}     # [linux]
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - {{ cdt('mesa-libegl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}   # [linux]
    - {{ cdt('libselinux') }}         # [linux]
    - {{ cdt('libxdamage') }}         # [linux]
    - {{ cdt('libxfixes') }}          # [linux]
    - {{ cdt('libxxf86vm') }}         # [linux]
    - {{ cdt('libxext') }}            # [linux]
    - {{ cdt('libxau') }}             # [linux]
    - {{ cdt('libxcb') }}             # [linux]
  host:
    - catch2
    - eigen
    - epoxy
    - fmt
    - glew
    - libglu             # [linux]
    - libpng
    - libxkbcommon       # [linux]
    - spdlog
    - xorg-libx11        # [linux]
    - xorg-libxext       # [linux]
    - xorg-libxfixes     # [linux]
    - zstd
  run:
    - xorg-libx11
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/cmake/Pangolin/PangolinConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\Pangolin\\PangolinConfig.cmake exit 1  # [win]

about:
  home: https://github.com/stevenlovegrove/Pangolin.git
  license: MIT
  license_file: LICENCE
  summary: Pangolin - A set of lightweight and portable utility libraries for prototyping 3D, numeric or video based programs and algorithms.
  dev_url: https://github.com/stevenlovegrove/Pangolin

extra:
  recipe-maintainers:
    - jeongseok-meta
