{% set name = "pangolin-opengl" %}
{% set version = "0.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 348f5c082d69afbb74b1af022d193cc0018ef8032a39409eb3f99c4ac2dd4b1e

build:
  number: 3
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - ninja
    - catch2
    - cmake
    - pkg-config  
    - libgl-devel  # [linux]
    - libglu       # [linux]
    - xorg-libx11
    - xorg-libxext
    - xorg-libxfixes
  host:
    - eigen
    - epoxy
    - glew
    - libpng
    - libxkbcommon       # [linux]
    - wayland            # [linux]
    - wayland-protocols  # [linux] 
    - zstd
  run:
    - xorg-libx11
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/cmake/Pangolin/PangolinConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\Pangolin\\PangolinConfig.cmake exit 1  # [win]

about:
  home: https://github.com/stevenlovegrove/Pangolin.git
  license: MIT
  license_file: LICENCE
  summary: Pangolin - A set of lightweight and portable utility libraries for prototyping 3D, numeric or video based programs and algorithms.
  dev_url: https://github.com/stevenlovegrove/Pangolin

extra:
  recipe-maintainers:
    - jeongseok-meta
