{% set name = "pangolin-opengl" %}
{% set version = "0.9.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fb95a354dc64bb151881192703db461a59089f7bcdb2c2c9185cfb5393586d97
  patches:
    - patches/0001-remove-werror.patch
    - patches/0002-fix-tinyobj-uninit.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - ninja
    - cmake
    - pkg-config
  host:
    - catch2
    - eigen
    - epoxy
    - fmt
    - glew
    - libegl-devel       # [linux]
    - libgl-devel        # [linux]
    - libglu             # [linux]
    - libglvnd-devel     # [linux]
    - libglx-devel       # [linux]
    - libopengl-devel    # [linux]
    - libpng
    - libxkbcommon       # [linux]
    - spdlog
    - xorg-libx11        # [linux]
    - xorg-libxext       # [linux]
    - xorg-libxfixes     # [linux]
    - zstd
  run:
    - xorg-libx11
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/cmake/Pangolin/PangolinConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\Pangolin\\PangolinConfig.cmake exit 1  # [win]

about:
  home: https://github.com/stevenlovegrove/Pangolin.git
  license: MIT
  license_file: LICENCE
  summary: Pangolin - A set of lightweight and portable utility libraries for prototyping 3D, numeric or video based programs and algorithms.
  dev_url: https://github.com/stevenlovegrove/Pangolin

extra:
  recipe-maintainers:
    - jeongseok-meta
