schema_version: 1

context:
  name: pangolin-opengl
  version: "0.9.6"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 43d49b53f897e79136e33da4071370d43d9e003b476216824cf22b627da19479
  patches:
    - patches/0001-remove-werror.patch
    - patches/0002-fix-tinyobj-uninit.patch
    - patches/0003-find-threads-in-config.patch

build:
  number: 0
  script:
    - if: unix
      then: bash "${RECIPE_DIR}/build.sh"
    - if: win
      then: call "%RECIPE_DIR%\\build.bat"

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - cmake
    - pkg-config
  host:
    - catch2
    - eigen
    - epoxy
    - fmt
    - glew
    - if: linux
      then:
        - libegl-devel
        - libgl-devel
        - libglu
        - libglvnd-devel
        - libglx-devel
        - libopengl-devel
    - libpng
    - if: linux
      then: libxkbcommon
    - spdlog
    - if: linux
      then:
        - xorg-libx11
        - xorg-libxext
        - xorg-libxfixes
    - zstd
  run:
    - xorg-libx11
    - zstd
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - files:
      recipe:
        - tests/
    requirements:
      run:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - eigen
        - if: linux
          then:
            - libegl-devel
            - libgl-devel
            - libopengl-devel
        - if: not win
          then: ninja
    script:
      - if: not win
        then:
          - test -f $PREFIX/lib/cmake/Pangolin/PangolinConfig.cmake
          - cmake -S tests -B tests/build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PREFIX
          - cmake --build tests/build --config Release
          - ctest --test-dir tests/build --output-on-failure
        else:
          - if not exist %PREFIX%\\Library\\lib\\cmake\\Pangolin\\PangolinConfig.cmake exit 1
          - cmake -S tests -B tests\\build -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX%
          - cmake --build tests\\build --config Release
          - ctest --test-dir tests\\build --output-on-failure -C Release
about:
  license: MIT
  license_file: LICENCE
  summary: Pangolin - A set of lightweight and portable utility libraries for prototyping 3D, numeric or video based programs and algorithms.
  homepage: https://github.com/stevenlovegrove/Pangolin.git
  repository: https://github.com/stevenlovegrove/Pangolin

extra:
  recipe-maintainers:
    - jeongseok-meta
